apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tagsdev-ingress
  annotations:
    gethomepage.dev/description: "TagsDev | Mark Taguaid"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Links
    gethomepage.dev/icon: https://raw.githubusercontent.com/mcbtaguiad/web-tagsdev-hugo/main/app/static/images/fa-tags-nobg.png
    gethomepage.dev/name: TagsDev
    # kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - tagsdev.xyz
    secretName: tagsdev-tls
  rules:
  - host: tagsdev.xyz
    http:
      paths:
      - path: /
        #pathType: ImplementationSpecific
        pathType: Prefix
        backend:
          service: 
            name: web-tagsdev
            port:
              number: 80